class item():
	def __init__(self,identifier,name,description,mass,price,units):
		self.id = identifier  
		self.name = name
		self.desc = description
		self.mass = mass
		self.price = price
		self.units = units

beer_bottle_empty = item('bottle', 'an empty beer bottle','This could be dangerous.',6,0,0)
glass_empty = item('glass','an empty glass','A relic of times gone by.',4.2,0,0)
keys = item('keys','keys','the keys to your flat',0,0,0)
wallet = item('wallet','wallet','',0,0,0)
phone = item('phone','phone','Your gateway to a Dragon taxi home.',0,0,0)
your_id = item('id','your id','Don\'t lose this.',0,0,0)
drugs = item('drugs','drugs','some suspicious white powder',4.2,0,0)
hipflask = item('hipflask','hipflask','A cheapskates pride and joy.',4.2,0,5)
jacket = item('jacket','your jacket','Keeps you warm, too warm.',4.2,0,0)
vk = item('vk','a bottle of vk','The sweet nectar of the gods.',4.2,1,1)
rum_coke = item('rum coke','rum and coke','Suboptimal drink.',4.2,3,2)
gin_tonic = item('gin tonic','gin and tonic','Mature student?',4.2,3,2)
vodka_shot = item('vodka shot','shot of vodka','Bread and butter of a night out.',4.2,2,2)
jager_bomb = item('jagerbomb','Jägerbomb','You don\'t know why you drink these',4.2,2,2)
water = item('water','glass of water','a glass of water',4.2,0,-1)
dark_fruits = item('dark fruits','can of dark fruits','Reminds you of your year 10 campouts.',4.2,3,2)
red_stripe = item('red stripe','can of red stripe','Jamaican you drunk',4.2,3,2)
pint_brains = item('brains','pint of brains','You unleash your inner welshman.',4.2,2,2)
bloody_mary = item('bloody mary','bloody mary cocktail','A questionable decision.',4.2,4,2)
sourz_shot = item('sourz','shot of sourz','A very distinct flavour.',4.2,2,1)
sambuca_shot = item('sambuca','shot of sambuca','A shot of sambuca.',4.2,2,2)
whiskey_shot = item('whiskey','shot of whiskey','Tastes like scotland.',4.2,3,2)
tequila_shot = item('tequila','shot of tequila','Ariba Ariba',4.2,2,2)
wine = item('wine','bottle of wine','Only the finest 2017 Lidl Pinot Grigio.',4.2,7,5)
cheeseburger = item('cheeseburger','cheeseburger','A wonderous creation.',4.2,1,-1)
chicken_nuggets = item('nuggets','chicken nuggets','You hope it\'s chicken.',4.2,4,-2)
mayo_chicken = item('mayo chicken','mayo chicken','Chicken slathered in mayo.',4.2,1,-1)
wrap_of_the_day = item('wrap','wrap of the day','More like wrap of the night :DDDDDDDDDDDDDDDDDDDDD',4.2,2,-1)
chips = item('chips','chips','Greasier than a car engine.',4.2,2,-2)
bigmac = item('bigmac','bigmac','The top dog.',4.2,3,-2)
mcflurry = item('mcflurry','mcflurry','To cool down after a busy night.',4.2,1,0)
kebab = item('kebab','kebab','Magical mystery meet.',4.2,3,-2)
a_cheeky_wink = item('wink','a cheeky wink', 'this wink will sure be successful',0,0,0)
