class item():
	def __init__(self,identifier,name,description,mass,price,units):
		self.id = identifier  
		self.name = name
		self.desc = description
		self.mass = mass
		self.price = price
		self.units = units

beer_bottle_empty = item('bottle', 'an empty beer bottle','description',6,0,0)
glass_empty = item('glass','an empty glass','description',4.2,0,0)
keys = item('keys','keys','the keys to your flat',0,0,0)
wallet = item('wallet','wallet','description',0,0,0)
phone = item('phone','phone','description',0,0,0)
your_id = item('id','your id','description',0,0,0)
drugs = item('drugs','drugs','some suspicious white powder',4.2,0,0)
hipflask = item('hipflask','hipflask','description',4.2,0,5)
jacket = item('jacket','your jacket','description',4.2,0,0)
vk = item('vk','a bottle of vk','description',4.2,1,1)
rum_coke = item('rum coke','rum and coke','description',4.2,3,2)
gin_tonic = item('gin tonic','gin and tonic','description',4.2,3,2)
vodka_shot = item('vodka shot','shot of vodka','description',4.2,2,2)
jager_bomb = item('jagerbomb','Jägerbomb','description',4.2,2,2)
water = item('water','glass of water','a glass of water',4.2,0,-1)
dark_fruits = item('dark fruits','can of dark fruits','description',4.2,3,2)
red_stripe = item('red stripe','can of red stripe','description',4.2,3,2)
pint_brains = item('brains','pint of brains','description',4.2,2,2)
bloody_mary = item('bloody mary','bloody mary cocktail','description',4.2,4,2)
sourz_shot = item('sourz','shot of sourz','description',4.2,2,1)
sambuca_shot = item('sambuca','shot of sambuca','description',4.2,2,2)
whiskey_coke = item('whiskey coke','shot of wiskey','description',4.2,3,2)
tequila_shot = item('tequila','shot of tequila','description',4.2,2,2)
wine = item('wine','bottle of wine','description',4.2,7,5)
cheeseburger = item('cheeseburger','cheeseburger','description',4.2,1,-1)
chicken_nuggets = item('nuggets','chicken nuggets','description',4.2,4,-2)
mayo_chicken = item('mayo chicken','mayo chicken','description',4.2,1,-1)
wrap_of_the_day = item('wrap','wrap of the day','description',4.2,2,-1)
chips = item('chips','chips','description',4.2,2,-2)
bigmac = item('bigmac','bigmac','description',4.2,3,-2)
mcflurry = item('mcflurry','mcflurry','description',4.2,1,0)
kebab = item('kebab','kebab','description',4.2,3,-2)
irish_disco_biscuit = item('irish disco biscuit','irish disco biscuit','description',4,4,3)
